server:
  port: 8089
spring:
  application:
    name: HW3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5447/hw3
    username: sumkin
    password: hw26032024
    driver-class-name: org.postgresql.Driver
logging:
  config: classpath:log4j2.xml




